spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/guarani_orders_dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

logging:
  level:
    com.guarani.ordersystem: TRACE
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true