spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  h2:
    console:
      enabled: false

logging:
  level:
    com.guarani.ordersystem: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN

app:
  security:
    jwt:
      secret: testSecretKeyForTestingPurposesOnly2024testSecretKeyForTestingPurposesOnly2024
      expiration: 3600000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false